# Generated by Django 3.1.1 on 2020-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
    ]
